name: Publish distribution 📦 to PyPI and TestPyPI
on: [push]
jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    
    # Build
    - name: Setup Python virtual environment
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-virtualenv
    - name: Initialize Python virtual environment
      run: |
        python3.8 -m venv venv
    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install --upgrade pip
        pip install build
        pip install wheel
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        deactivate
    - name: Build a binary wheel and a source tarball
      run: |
        source venv/bin/activate
        python3.8 -m build --sdist --wheel --outdir dist
        deactivate
    - name: Install a builded package
      run: |
        source venv/bin/activate
        python3.8 -m setup install
        deactivate
    - name: Test with pytest
      run: |
        source venv/bin/activate
        python3.8 -m pytest
        deactivate
    # Publish
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

